namespace ObsidianAI.Domain.Entities;

/// <summary>
/// Identifies the LLM provider associated with a conversation.
/// </summary>
public enum ConversationProvider
{
    Unknown = 0,
    LmStudio = 1,
    OpenRouter = 2
}

/// <summary>
/// Role of a message author within a conversation transcript.
/// </summary>
public enum MessageRole
{
    System = 0,
    User = 1,
    Assistant = 2
}

/// <summary>
/// Status assigned to an action card generated by the assistant.
/// </summary>
public enum ActionCardStatus
{
    Pending = 0,
    Confirmed = 1,
    Processing = 2,
    Completed = 3,
    Failed = 4,
    Cancelled = 5
}

/// <summary>
/// Distinguished types of planned actions contained within a card.
/// </summary>
public enum PlannedActionType
{
    Create = 0,
    Modify = 1,
    Move = 2,
    Delete = 3,
    Copy = 4,
    Rename = 5,
    Other = 6
}
